/**
 * Local question fallback — used when the remote API returns no questions.
 *
 * Key format:
 *   Simple levels:        "${levelCode}/${subject}/${chapterName}"
 *   Section levels:       "${levelCode}/${sectionKey}/${subject}/${chapterName}"
 *
 * Chapter names MUST match curriculumFallback.ts exactly.
 * IDs are negative to distinguish from real DB rows.
 *
 * Schema:
 *   - multiple-choice: instruction + question + options[A..D] + correctAnswer (letter) + explanation
 *   - problem-solving: instruction + question + correctAnswer (text) + explanation
 *   - short-answer:    instruction + question + correctAnswer (text) + explanation
 *
 * Student-facing UI shows: instruction → question → options → points.
 * correctAnswer and explanation are hidden until the student reveals the mark scheme.
 */

export type FallbackQuestionType = "multiple-choice" | "problem-solving" | "short-answer";

export interface FallbackOption {
  label: "A" | "B" | "C" | "D";
  text:  string;
}

export interface FallbackQuestion {
  id:                   number;
  type:                 FallbackQuestionType;
  instruction:          string;
  question:             string;
  options?:             FallbackOption[];
  correctAnswer:        string;
  explanation:          string;
  difficulty:           "facile" | "moyen" | "difficile";
  totalMarks:           number;
  estimatedTimeMinutes: number;
  requiresCalculator:   boolean;
  direction:            "ltr" | "rtl";
  source:               "manual-starter" | "manual-starter-2eme" | "manual-starter-3eme";
}

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────

function mcq(
  id: number,
  question: string,
  options: [string, string, string, string],
  correctAnswer: "A" | "B" | "C" | "D",
  explanation: string,
  opts: { difficulty?: FallbackQuestion["difficulty"]; marks?: number; minutes?: number; calc?: boolean; rtl?: boolean } = {},
): FallbackQuestion {
  const rtl = opts.rtl ?? false;
  return {
    id,
    type: "multiple-choice",
    instruction: rtl ? "اختر الإجابة الصحيحة." : "a) Choisissez la bonne réponse.",
    question,
    options: [
      { label: "A", text: options[0] },
      { label: "B", text: options[1] },
      { label: "C", text: options[2] },
      { label: "D", text: options[3] },
    ],
    correctAnswer,
    explanation,
    difficulty: opts.difficulty ?? "facile",
    totalMarks: opts.marks ?? 2,
    estimatedTimeMinutes: opts.minutes ?? 3,
    requiresCalculator: opts.calc ?? false,
    direction: rtl ? "rtl" : "ltr",
    source: "manual-starter",
  };
}

function problem(
  id: number,
  question: string,
  correctAnswer: string,
  explanation: string,
  opts: { difficulty?: FallbackQuestion["difficulty"]; marks?: number; minutes?: number; calc?: boolean; rtl?: boolean } = {},
): FallbackQuestion {
  const rtl = opts.rtl ?? false;
  return {
    id,
    type: "problem-solving",
    instruction: rtl ? "حلّ المسألة التالية." : "Résolvez le problème suivant.",
    question,
    correctAnswer,
    explanation,
    difficulty: opts.difficulty ?? "moyen",
    totalMarks: opts.marks ?? 3,
    estimatedTimeMinutes: opts.minutes ?? 5,
    requiresCalculator: opts.calc ?? false,
    direction: rtl ? "rtl" : "ltr",
    source: "manual-starter",
  };
}

function shortAnswer(
  id: number,
  question: string,
  correctAnswer: string,
  explanation: string,
  opts: { difficulty?: FallbackQuestion["difficulty"]; marks?: number; minutes?: number; rtl?: boolean } = {},
): FallbackQuestion {
  const rtl = opts.rtl ?? false;
  return {
    id,
    type: "short-answer",
    instruction: rtl ? "أجب عن السؤال التالي." : "Répondez brièvement.",
    question,
    correctAnswer,
    explanation,
    difficulty: opts.difficulty ?? "facile",
    totalMarks: opts.marks ?? 2,
    estimatedTimeMinutes: opts.minutes ?? 3,
    requiresCalculator: false,
    direction: rtl ? "rtl" : "ltr",
    source: "manual-starter",
  };
}

// ──────────────────────────────────────────────────────────────────────────────
// 1ÈRE SECONDAIRE — MATHÉMATIQUES (20 questions)
// ──────────────────────────────────────────────────────────────────────────────

const MATH_1ERE: Record<string, FallbackQuestion[]> = {
  "1ere_secondaire/Mathématiques/Angles": [
    mcq(-101,
      "Deux angles mesurent 35° et 55°. Que peut-on dire de ces deux angles ?",
      ["Ils sont supplémentaires", "Ils sont complémentaires", "Ils sont opposés par le sommet", "Ils sont alternes-internes"],
      "B",
      "35° + 55° = 90°, donc les deux angles sont complémentaires.",
      { difficulty: "facile" },
    ),
    problem(-102,
      "Deux angles supplémentaires sont tels que l'un mesure 70°. Calcule la mesure de l'autre angle.",
      "110°",
      "Deux angles supplémentaires ont une somme de 180°. Donc l'autre angle mesure 180° − 70° = 110°.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
  ],
  "1ere_secondaire/Mathématiques/Théorème de Thalès et sa réciproque": [
    problem(-103,
      "Dans un triangle ABC, les points M et N appartiennent respectivement aux côtés [AB] et [AC], et (MN) est parallèle à (BC). On donne AM = 3 cm, AB = 9 cm et AC = 12 cm. Calcule AN.",
      "AN = 4 cm",
      "D'après le théorème de Thalès, AM / AB = AN / AC. Donc 3 / 9 = AN / 12. Alors AN = 12 × 3 / 9 = 4 cm.",
      { difficulty: "moyen", marks: 3, minutes: 6 },
    ),
    mcq(-104,
      "Le théorème de Thalès s'applique lorsque :",
      ["Les droites sont perpendiculaires", "Les droites sont parallèles et coupent deux sécantes", "Les triangles sont équilatéraux", "Les angles sont droits"],
      "B",
      "Le théorème de Thalès s'applique à deux droites parallèles coupées par deux sécantes.",
      { difficulty: "facile" },
    ),
  ],
  "1ere_secondaire/Mathématiques/Rapports trigonométriques d'un angle aigu; Relations métriques dans un triangle rectangle": [
    mcq(-105,
      "Dans un triangle rectangle, pour un angle aigu A, quelle formule donne cos(A) ?",
      ["côté opposé / hypoténuse", "côté adjacent / hypoténuse", "côté opposé / côté adjacent", "hypoténuse / côté adjacent"],
      "B",
      "Dans un triangle rectangle, cos(A) = côté adjacent à A / hypoténuse.",
      { difficulty: "facile" },
    ),
    problem(-106,
      "Dans un triangle rectangle, l'hypoténuse mesure 10 cm et le côté adjacent à l'angle A mesure 8 cm. Calcule cos(A).",
      "cos(A) = 0,8",
      "cos(A) = côté adjacent / hypoténuse = 8 / 10 = 0,8.",
      { difficulty: "moyen", marks: 2, minutes: 4 },
    ),
  ],
  "1ere_secondaire/Mathématiques/Vecteurs et translations": [
    mcq(-107,
      "Une translation de vecteur u transforme un point A en un point A'. Quelle relation est correcte ?",
      ["A'A = u", "AA' = u", "AA' = -u", "A'A = 0"],
      "B",
      "Par définition, la translation de vecteur u transforme A en A' tel que AA' = u.",
      { difficulty: "facile" },
    ),
  ],
  "1ere_secondaire/Mathématiques/Somme de deux vecteurs - Vecteurs colinéaires": [
    mcq(-108,
      "Deux vecteurs sont colinéaires lorsqu'ils :",
      ["ont toujours la même longueur", "ont des directions parallèles", "sont toujours perpendiculaires", "ont toujours le même sens"],
      "B",
      "Deux vecteurs sont colinéaires s'ils ont la même direction ou des directions parallèles.",
      { difficulty: "facile" },
    ),
    problem(-109,
      "On donne deux vecteurs u(2 ; 3) et v(4 ; 6). Ces deux vecteurs sont-ils colinéaires ?",
      "Oui, v = 2u, donc ils sont colinéaires.",
      "On vérifie si v est un multiple de u : v = (4 ; 6) = 2 × (2 ; 3) = 2u. Donc les deux vecteurs sont colinéaires.",
      { difficulty: "moyen" },
    ),
  ],
  "1ere_secondaire/Mathématiques/Activités dans un repère": [
    problem(-110,
      "Dans un repère, on donne A(2 ; 3) et B(6 ; 3). Calcule la distance AB.",
      "AB = 4",
      "Les deux points ont la même ordonnée. La distance horizontale est donc |6 − 2| = 4.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
  ],
  "1ere_secondaire/Mathématiques/Quart de tour": [
    mcq(-111,
      "Un quart de tour direct correspond à une rotation d'angle :",
      ["+45°", "+90°", "+180°", "−90°"],
      "B",
      "Un quart de tour direct est une rotation de +90° (sens trigonométrique).",
      { difficulty: "facile" },
    ),
  ],
  "1ere_secondaire/Mathématiques/Sections planes d'un solide": [
    mcq(-112,
      "La section d'un cube par un plan parallèle à une face est :",
      ["un triangle", "un cercle", "un carré identique à la face", "un rectangle quelconque"],
      "C",
      "Couper un cube avec un plan parallèle à l'une de ses faces donne un carré de mêmes dimensions que cette face.",
      { difficulty: "facile" },
    ),
  ],
  "1ere_secondaire/Mathématiques/Activités numériques I": [
    problem(-113,
      "Calcule : A = (−3) × (−4) + 2 × (−5).",
      "A = 2",
      "(−3) × (−4) = 12 et 2 × (−5) = −10. Donc A = 12 − 10 = 2.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
  ],
  "1ere_secondaire/Mathématiques/Activités numériques II": [
    problem(-114,
      "Écris sous la forme d'une seule puissance : B = 2³ × 2⁵.",
      "B = 2⁸",
      "Lorsque l'on multiplie deux puissances d'un même nombre, on additionne les exposants : 2³ × 2⁵ = 2³⁺⁵ = 2⁸.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
  ],
  "1ere_secondaire/Mathématiques/Activités algébriques": [
    problem(-115,
      "Développe et réduis : C = (x + 3)(x − 2).",
      "C = x² + x − 6",
      "C = x × x − 2x + 3x − 6 = x² + x − 6.",
      { difficulty: "moyen", marks: 3, minutes: 5 },
    ),
  ],
  "1ere_secondaire/Mathématiques/Fonctions linéaires": [
    problem(-116,
      "Soit la fonction linéaire f définie par f(x) = 3x. Calcule f(5).",
      "f(5) = 15",
      "On remplace x par 5 : f(5) = 3 × 5 = 15.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
    mcq(-117,
      "Une fonction linéaire est représentée graphiquement par :",
      ["une parabole", "une droite passant par l'origine", "une droite quelconque", "un cercle"],
      "B",
      "Une fonction linéaire f(x) = ax est représentée par une droite qui passe par l'origine du repère.",
      { difficulty: "facile" },
    ),
  ],
  "1ere_secondaire/Mathématiques/Équations et inéquations du premier degré à une inconnue": [
    problem(-118,
      "Résous l'équation 4x − 5 = 19.",
      "x = 6",
      "4x − 5 = 19 donne 4x = 24, donc x = 24 / 4 = 6.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
  ],
  "1ere_secondaire/Mathématiques/Fonctions affines": [
    mcq(-119,
      "Laquelle des fonctions suivantes est une fonction affine ?",
      ["f(x) = 5x", "f(x) = 2x + 3", "f(x) = x²", "f(x) = 1 / x"],
      "B",
      "Une fonction affine est de la forme f(x) = ax + b avec b ≠ 0. Ici, f(x) = 2x + 3 est une fonction affine.",
      { difficulty: "facile" },
    ),
  ],
  "1ere_secondaire/Mathématiques/Systèmes de deux équations à deux inconnues": [
    problem(-120,
      "Résous le système : { x + y = 7 ; x − y = 1 }.",
      "x = 4 ; y = 3",
      "En additionnant les deux équations : 2x = 8, donc x = 4. Puis y = 7 − 4 = 3.",
      { difficulty: "moyen", marks: 3, minutes: 5 },
    ),
  ],
  "1ere_secondaire/Mathématiques/Exploitation de l'information": [
    problem(-121,
      "Les notes d'un élève sont : 12, 14, 10, 16, 13. Calcule la moyenne arithmétique.",
      "13",
      "Moyenne = (12 + 14 + 10 + 16 + 13) / 5 = 65 / 5 = 13.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
  ],
};

// ──────────────────────────────────────────────────────────────────────────────
// 1ÈRE SECONDAIRE — PHYSIQUE-CHIMIE (20 questions)
// ──────────────────────────────────────────────────────────────────────────────

const PHYSIQUE_1ERE: Record<string, FallbackQuestion[]> = {
  "1ere_secondaire/Physique-Chimie/Le phénomène d'électrisation": [
    mcq(-201,
      "Lorsqu'on frotte un bâton en plastique avec un chiffon en laine, il devient capable d'attirer de petits morceaux de papier. Ce phénomène s'appelle :",
      ["la fusion", "l'électrisation", "la condensation", "la fission"],
      "B",
      "Le frottement transfère des électrons et électrise le bâton, qui attire alors les petits objets légers.",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/Le circuit électrique": [
    mcq(-202,
      "Une lampe ne s'allume pas dans un circuit simple. Quelle situation explique le mieux cela ?",
      ["Le circuit est fermé", "Le circuit est ouvert", "La lampe reçoit du courant", "Le générateur fonctionne toujours même sans circuit fermé"],
      "B",
      "Pour qu'un courant circule et que la lampe s'allume, le circuit doit être fermé. Si le circuit est ouvert, la lampe ne s'allume pas.",
    ),
    shortAnswer(-203,
      "Cite les trois éléments indispensables pour réaliser un circuit électrique simple qui allume une lampe.",
      "Un générateur, des fils de connexion et un récepteur (lampe).",
      "Un circuit électrique simple nécessite une source d'énergie (générateur), un conducteur (fils) et un récepteur (lampe).",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/L'intensité du courant électrique": [
    problem(-204,
      "Un ampèremètre indique 0,25 A dans un circuit. Exprime cette intensité en milliampères.",
      "250 mA",
      "1 A = 1000 mA, donc 0,25 A = 0,25 × 1000 = 250 mA.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
    mcq(-205,
      "L'instrument qui sert à mesurer l'intensité d'un courant électrique est :",
      ["le voltmètre", "l'ampèremètre", "l'ohmmètre", "le thermomètre"],
      "B",
      "L'ampèremètre mesure l'intensité du courant. Il se branche en série dans le circuit.",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/La tension électrique": [
    problem(-206,
      "Deux piles identiques de 3 V sont associées en série. Quelle tension totale fournissent-elles ?",
      "6 V",
      "En série, les tensions des piles s'additionnent : 3 V + 3 V = 6 V.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
    mcq(-207,
      "Le voltmètre se branche dans un circuit :",
      ["en série avec la lampe", "en dérivation aux bornes du dipôle", "à la place du générateur", "n'importe comment"],
      "B",
      "Le voltmètre mesure la tension aux bornes d'un dipôle : il se branche toujours en dérivation.",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/Le dipôle résistor": [
    mcq(-208,
      "Dans un circuit, un résistor sert principalement à :",
      ["produire de la lumière", "limiter l'intensité du courant", "mesurer la tension", "ouvrir automatiquement le circuit"],
      "B",
      "Un résistor s'oppose au passage du courant et permet de limiter l'intensité dans une portion de circuit.",
    ),
    problem(-209,
      "On applique une tension de 12 V aux bornes d'un résistor de résistance 6 Ω. Calcule l'intensité du courant.",
      "I = 2 A",
      "D'après la loi d'Ohm, U = R × I. Donc I = U / R = 12 / 6 = 2 A.",
      { difficulty: "moyen", marks: 3, minutes: 5 },
    ),
  ],
  "1ere_secondaire/Physique-Chimie/Les états physiques de la matière": [
    mcq(-210,
      "Lorsqu'un glaçon fond, quel changement d'état a lieu ?",
      ["solide vers liquide", "liquide vers gaz", "gaz vers liquide", "liquide vers solide"],
      "A",
      "La fusion est le passage de l'état solide à l'état liquide.",
    ),
    shortAnswer(-211,
      "Cite les trois états physiques de la matière.",
      "Solide, liquide et gazeux.",
      "Les trois états physiques de la matière sont : solide, liquide et gazeux.",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/La masse": [
    problem(-212,
      "Une boîte vide a une masse de 120 g. Remplie de sable, elle a une masse de 470 g. Quelle est la masse du sable ?",
      "350 g",
      "Masse du sable = masse totale − masse de la boîte vide = 470 − 120 = 350 g.",
      { difficulty: "facile", marks: 2, minutes: 3 },
    ),
  ],
  "1ere_secondaire/Physique-Chimie/Les changements d'état physique d'un corps pur": [
    mcq(-213,
      "Le passage de l'état liquide à l'état gazeux s'appelle :",
      ["fusion", "solidification", "vaporisation", "condensation"],
      "C",
      "La vaporisation est le passage de l'état liquide à l'état gazeux. Elle inclut l'évaporation et l'ébullition.",
    ),
    mcq(-214,
      "La température de fusion de la glace pure sous pression atmosphérique normale est :",
      ["−10 °C", "0 °C", "50 °C", "100 °C"],
      "B",
      "La glace fond à 0 °C sous une pression atmosphérique normale.",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/Atomes et ions simples": [
    mcq(-215,
      "L'atome d'oxygène possède 8 électrons. Le nombre de protons dans son noyau est :",
      ["6", "8", "10", "16"],
      "B",
      "Un atome est électriquement neutre : il possède autant de protons que d'électrons. Donc 8 protons.",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/Concentration d'une solution": [
    problem(-216,
      "On dissout 10 g de sel dans 500 mL d'eau. Calcule la concentration massique en g/L.",
      "20 g/L",
      "500 mL = 0,5 L. La concentration massique est C = m / V = 10 / 0,5 = 20 g/L.",
      { difficulty: "moyen", marks: 3, minutes: 5, calc: true },
    ),
  ],
  "1ere_secondaire/Physique-Chimie/Notion de réaction chimique": [
    mcq(-217,
      "Lors d'une réaction chimique, que deviennent les réactifs ?",
      ["Ils disparaissent pour former de nouveaux produits", "Ils restent toujours inchangés", "Ils deviennent uniquement plus chauds", "Ils changent seulement d'état physique"],
      "A",
      "Une réaction chimique transforme les réactifs en nouveaux produits avec des propriétés différentes.",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/Le mouvement": [
    mcq(-218,
      "Un objet est immobile par rapport au sol. Si on le regarde depuis une voiture en mouvement, on dit que :",
      ["il est immobile", "il est en mouvement par rapport à la voiture", "il accélère par lui-même", "il change de masse"],
      "B",
      "Le mouvement dépend du référentiel choisi : par rapport à la voiture qui bouge, l'objet immobile au sol semble en mouvement.",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/Forces et équilibre": [
    mcq(-219,
      "Un livre posé sur une table est en équilibre. Cela signifie que :",
      ["aucune force ne s'exerce sur lui", "les forces s'exerçant sur lui se compensent", "il avance lentement", "il accélère vers le sol"],
      "B",
      "Un objet en équilibre est soumis à des forces dont la somme est nulle. Le poids est compensé par la réaction de la table.",
    ),
  ],
  "1ere_secondaire/Physique-Chimie/La lumière et sa propagation": [
    mcq(-220,
      "Dans un milieu transparent et homogène, la lumière se propage :",
      ["en zigzag", "en ligne droite", "en cercle", "de façon imprévisible"],
      "B",
      "Dans un milieu transparent et homogène, la lumière se propage en ligne droite. C'est le principe de la propagation rectiligne.",
    ),
  ],
};

// ──────────────────────────────────────────────────────────────────────────────
// 1ÈRE SECONDAIRE — SCIENCES NATURELLES / SVT (16 questions, 2 per chapter)
// ──────────────────────────────────────────────────────────────────────────────

const SVT_1ERE: Record<string, FallbackQuestion[]> = {
  "1ere_secondaire/Sciences Naturelles/La nutrition minérale": [
    mcq(-301,
      "Quel organe permet à la plante d'absorber l'eau et les sels minéraux du sol ?",
      ["Les feuilles", "Les racines", "La tige", "Les fleurs"],
      "B",
      "Les racines, et notamment les poils absorbants, prélèvent l'eau et les sels minéraux du sol.",
    ),
    shortAnswer(-302,
      "Quel est le rôle des poils absorbants chez la plante ?",
      "Ils permettent l'absorption de l'eau et des sels minéraux du sol.",
      "Les poils absorbants, situés sur les racines jeunes, augmentent la surface d'échange avec le sol et permettent l'absorption.",
    ),
  ],
  "1ere_secondaire/Sciences Naturelles/La nutrition carbonée": [
    mcq(-303,
      "Quel gaz est nécessaire à la photosynthèse ?",
      ["Le dioxygène", "Le dioxyde de carbone", "L'azote", "La vapeur d'eau"],
      "B",
      "La photosynthèse utilise le dioxyde de carbone (CO₂) et de l'eau, en présence de lumière, pour produire de la matière organique et du dioxygène.",
    ),
    shortAnswer(-304,
      "Où se déroule la photosynthèse dans une plante verte ?",
      "Dans les chloroplastes des cellules des feuilles.",
      "Les chloroplastes contiennent la chlorophylle, qui capte la lumière nécessaire à la photosynthèse.",
    ),
  ],
  "1ere_secondaire/Sciences Naturelles/La multiplication végétative": [
    mcq(-305,
      "La multiplication végétative permet d'obtenir des plantes :",
      ["génétiquement identiques à la plante mère", "très différentes de la plante mère", "qui produisent toujours des graines", "qui n'ont jamais de racines"],
      "A",
      "La multiplication végétative est une reproduction asexuée : les nouvelles plantes sont des clones de la plante mère.",
    ),
    shortAnswer(-306,
      "Cite un exemple de technique utilisée par l'agriculteur pour multiplier une plante sans utiliser de graines.",
      "Le bouturage (ou le marcottage, ou le greffage).",
      "Ces techniques sont des formes de multiplication végétative qui permettent de reproduire fidèlement une plante choisie.",
    ),
  ],
  "1ere_secondaire/Sciences Naturelles/La diversité du monde microbien": [
    mcq(-307,
      "Parmi ces éléments, lequel n'est PAS un micro-organisme ?",
      ["Les bactéries", "Les virus", "Les champignons microscopiques", "Les insectes"],
      "D",
      "Bactéries, virus et champignons microscopiques sont des micro-organismes ; les insectes sont des animaux visibles à l'œil nu.",
    ),
    shortAnswer(-308,
      "Tous les microbes sont-ils dangereux pour l'homme ? Justifie en donnant un exemple.",
      "Non. Par exemple, les bactéries du yaourt ou de la levure du pain sont utiles.",
      "De nombreux microbes sont utiles : digestion, fabrication du fromage, du pain, du vinaigre, etc.",
    ),
  ],
  "1ere_secondaire/Sciences Naturelles/Les agents pathogènes et les maladies infectieuses": [
    mcq(-309,
      "Une maladie infectieuse est provoquée par :",
      ["une mauvaise alimentation", "un agent pathogène (bactérie, virus, parasite)", "un manque de sport", "le stress uniquement"],
      "B",
      "Une maladie infectieuse est due à la pénétration et à la multiplication d'un agent pathogène dans l'organisme.",
    ),
    shortAnswer(-310,
      "Cite deux moyens de prévenir la transmission des maladies infectieuses.",
      "Le lavage des mains et la vaccination (ou hygiène, distance physique).",
      "Hygiène (lavage des mains, eau propre) et vaccination sont des moyens efficaces de prévention.",
    ),
  ],
  "1ere_secondaire/Sciences Naturelles/La défense de l'organisme": [
    mcq(-311,
      "Quelles cellules du sang jouent un rôle essentiel dans la défense de l'organisme ?",
      ["Les globules rouges", "Les globules blancs", "Les plaquettes uniquement", "Le plasma"],
      "B",
      "Les globules blancs (leucocytes) sont les principales cellules de l'immunité : ils détectent et détruisent les agents pathogènes.",
    ),
    shortAnswer(-312,
      "Qu'est-ce qu'un vaccin ?",
      "Une préparation qui stimule les défenses immunitaires sans rendre malade, pour protéger contre un agent pathogène.",
      "Le vaccin contient une forme inactivée ou affaiblie de l'agent pathogène, ou ses fragments, et entraîne le système immunitaire.",
    ),
  ],
  "1ere_secondaire/Sciences Naturelles/Étude d'un site géologique": [
    mcq(-313,
      "Lors de l'étude d'un site géologique, on observe surtout :",
      ["les nuages", "les roches, leurs couches et leur disposition", "les animaux qui y vivent", "uniquement les couleurs du sol"],
      "B",
      "L'étude géologique d'un site consiste à observer les roches, les couches sédimentaires et leur organisation.",
    ),
  ],
  "1ere_secondaire/Sciences Naturelles/Exploitation et gestion d'une roche à intérêt économique: le phosphate": [
    mcq(-314,
      "Le phosphate est exploité en Tunisie principalement pour la fabrication de :",
      ["bijoux", "carburants", "engrais et acide phosphorique", "ciment uniquement"],
      "C",
      "Le phosphate tunisien est utilisé principalement pour produire des engrais et de l'acide phosphorique, importants pour l'agriculture et l'industrie.",
    ),
    shortAnswer(-315,
      "Pourquoi faut-il gérer durablement les ressources en phosphate ?",
      "Parce que c'est une ressource non renouvelable et que son exploitation a des impacts économiques et environnementaux importants.",
      "Le phosphate s'épuise avec le temps ; une gestion durable assure son utilisation pour les générations futures.",
    ),
  ],
};

// ──────────────────────────────────────────────────────────────────────────────
// 1ÈRE SECONDAIRE — FRANÇAIS (14 questions, 2 per module)
// ──────────────────────────────────────────────────────────────────────────────

const FRANCAIS_1ERE: Record<string, FallbackQuestion[]> = {
  "1ere_secondaire/Français/Module 1: Rencontres": [
    shortAnswer(-401,
      "Dans un récit, quel rôle peut jouer une rencontre importante ?",
      "Elle peut transformer la relation entre les personnages ou changer leur vision du monde.",
      "Une rencontre marquante est souvent un élément déclencheur ou un tournant dans le récit.",
    ),
    mcq(-402,
      "Quel temps verbal est le plus souvent utilisé pour raconter une rencontre passée dans un récit ?",
      ["Le futur simple", "Le passé simple ou le passé composé", "Le conditionnel", "L'impératif"],
      "B",
      "Le passé simple (ou le passé composé à l'oral et dans les récits modernes) est le temps de la narration au passé.",
    ),
  ],
  "1ere_secondaire/Français/Module 2: Scènes de la vie en France": [
    shortAnswer(-403,
      "Cite deux éléments de la vie quotidienne en France souvent décrits dans la littérature.",
      "Les cafés, les marchés (ou les rues, les écoles, les transports).",
      "Les écrivains aiment décrire les lieux familiers de la vie française : cafés, marchés, ruelles, etc.",
    ),
    mcq(-404,
      "Lequel de ces éléments est typique d'une description ?",
      ["Des dialogues rapides", "Des adjectifs et des compléments de lieu", "Une suite d'actions seulement", "Des verbes uniquement au futur"],
      "B",
      "La description fait appel à des adjectifs qualificatifs et à des indications de lieu pour faire voir une scène.",
    ),
  ],
  "1ere_secondaire/Français/Module 3: Jeunesse sans frontières": [
    shortAnswer(-405,
      "Donne un exemple d'engagement possible pour un jeune dans la société.",
      "Le bénévolat, l'engagement associatif, la protection de l'environnement, etc.",
      "Les jeunes peuvent s'engager par le bénévolat, des associations, des projets solidaires, etc.",
    ),
    mcq(-406,
      "Quel type de texte sert le mieux à défendre une opinion sur les jeunes dans la société ?",
      ["Un texte narratif", "Un texte argumentatif", "Un texte descriptif", "Un poème lyrique"],
      "B",
      "Le texte argumentatif sert à défendre une thèse ou un point de vue à l'aide d'arguments et d'exemples.",
    ),
  ],
  "1ere_secondaire/Français/Module 4: La société de consommation": [
    shortAnswer(-407,
      "Qu'est-ce que la société de consommation ?",
      "Une société où l'achat de biens et de services est encouragé et valorisé.",
      "Dans une société de consommation, on est incité à acheter et consommer pour stimuler l'économie.",
    ),
    mcq(-408,
      "Lequel de ces moyens vise principalement à inciter à la consommation ?",
      ["Le débat philosophique", "La publicité", "Les cours de mathématiques", "Les bulletins météo"],
      "B",
      "La publicité a pour objectif de faire connaître un produit et d'inciter à l'acheter.",
    ),
  ],
  "1ere_secondaire/Français/Module 5: Sauvons la planète Terre": [
    shortAnswer(-409,
      "Cite deux gestes simples pour protéger l'environnement au quotidien.",
      "Trier les déchets et économiser l'eau (ou l'électricité, le transport durable, etc.).",
      "De nombreux gestes individuels (tri, économies d'eau, mobilité douce) contribuent à protéger la planète.",
    ),
    mcq(-410,
      "Quel connecteur logique exprime la cause ?",
      ["Parce que", "Donc", "Mais", "Pourtant"],
      "A",
      "« Parce que » exprime la cause ; « donc » exprime la conséquence ; « mais / pourtant » expriment l'opposition.",
    ),
  ],
  "1ere_secondaire/Français/Module 6: Passions": [
    shortAnswer(-411,
      "Donne un exemple de passion qu'on peut développer pendant l'adolescence.",
      "La musique, le sport, la lecture, le dessin, etc.",
      "Les passions enrichissent la personnalité et permettent l'épanouissement personnel.",
    ),
    mcq(-412,
      "Pour exprimer un sentiment fort comme la passion, on utilise souvent :",
      ["des adjectifs neutres", "des adjectifs intensifs et des figures de style", "des chiffres", "des symboles mathématiques"],
      "B",
      "Les figures de style (métaphores, comparaisons) et les adjectifs intensifs (immense, ardent, etc.) renforcent l'expression d'un sentiment.",
    ),
  ],
  "1ere_secondaire/Français/Module 7: Progrès et bonheur": [
    shortAnswer(-413,
      "Le progrès scientifique apporte-t-il toujours le bonheur ? Justifie en une phrase.",
      "Non, il peut aussi créer de nouveaux problèmes (pollution, inégalités, dépendance technologique).",
      "Le progrès a des aspects positifs (santé, confort) et négatifs (environnement, déshumanisation) qu'il faut nuancer.",
    ),
    mcq(-413 - 1,
      "Dans un texte argumentatif, quelle partie présente la position de l'auteur ?",
      ["L'introduction (thèse)", "Une simple description", "Le titre uniquement", "Aucune partie"],
      "A",
      "L'introduction d'un texte argumentatif présente la thèse, c'est-à-dire la position défendue par l'auteur.",
    ),
  ],
};

// ──────────────────────────────────────────────────────────────────────────────
// 1ÈRE SECONDAIRE — HISTOIRE (Arabic, RTL, ≥ 20 questions)
// ──────────────────────────────────────────────────────────────────────────────

const HISTOIRE_1ERE: Record<string, FallbackQuestion[]> = {
  "1ere_secondaire/Histoire/الخصوصيات الحضارية": [
    shortAnswer(-501,
      "اذكر اثنتين من خصوصيات الحضارة القرطاجية.",
      "النشاط التجاري البحري واللغة البونية والديانة الخاصة.",
      "تميّزت قرطاج بنشاطها التجاري المتوسطي ولغتها البونية ومعتقداتها الدينية وطرز عمارتها.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/المؤسسات السياسية": [
    mcq(-502,
      "من كان يتولى السلطة العليا في قرطاج البونية؟",
      ["ملك مطلق", "السوفاطيون ومجلس الشيوخ", "إمبراطور روماني", "خليفة"],
      "B",
      "كانت قرطاج تُدار من قبل السوفاطين (سوفاط) ومجلس الشيوخ مع مشاركة الجمعية الشعبية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/الديانة": [
    shortAnswer(-503,
      "اذكر معبودَين رئيسيَّين عند القرطاجيين.",
      "بعل حمون وتانيت.",
      "كان بعل حمون كبير الآلهة، وتانيت الإلهة الأم؛ وكانا في مركز الديانة القرطاجية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/إشعاع قرطاج": [
    shortAnswer(-504,
      "ما أهمية قرطاج في المتوسط القديم؟",
      "كانت قرطاج قطباً حضارياً وتجارياً مهماً، اشتهرت بمينائها وتوسعها التجاري وإشعاعها الحضاري.",
      "أسهمت قرطاج في نشر الحضارة البونية حول المتوسط من خلال التجارة والاستعمار الفينيقي والملاحة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/الميناء والتوسع التجاري": [
    mcq(-505,
      "ما الميزة التي اشتهر بها ميناء قرطاج؟",
      ["كان مينائاً صغيراً للصيد فقط", "كان مينائاً تجارياً وحربياً ذا تخطيط متطور", "لم يكن له دور اقتصادي", "كان مخصصاً للزراعة"],
      "B",
      "تميّز ميناء قرطاج بتخطيطه المتطور الذي يضم حوضاً تجارياً وآخر حربياً، مما عزّز قوتها البحرية والاقتصادية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/موسوعة ماغون": [
    shortAnswer(-506,
      "بِم اشتهرت موسوعة ماغون؟",
      "بأنها موسوعة قرطاجية في الفلاحة، تُرجمت إلى لغات عدة.",
      "كتب ماغون موسوعةً في الفلاحة والاقتصاد الزراعي، تُرجمت إلى اللاتينية واليونانية بعد سقوط قرطاج.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/عبقرية حنبعل": [
    mcq(-507,
      "اشتهر حنبعل بقيادته العسكرية أثناء:",
      ["الحرب البونية الأولى", "الحرب البونية الثانية", "غزو مصر", "حروب الفرس"],
      "B",
      "قاد حنبعل القرطاجيين خلال الحرب البونية الثانية، واشتهر بعبوره جبال الألب لمواجهة الرومان.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/الازدهار العمراني": [
    shortAnswer(-508,
      "اذكر أحد مظاهر الازدهار العمراني في قرطاج الرومانية.",
      "بناء الحمامات والمسارح والمعابد والشوارع المنظمة.",
      "ازدهرت قرطاج في العهد الروماني بفضل بناء حمامات أنطونيوس والمسارح والمدرّجات والشبكات الحضرية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/الازدهار الاقتصادي: الفلاحة": [
    mcq(-509,
      "ما المنتوج الفلاحي الذي اشتهرت به إفريقية الرومانية؟",
      ["الموز", "الزيتون والحبوب", "البن", "الأرز"],
      "B",
      "اشتهرت إفريقية الرومانية بإنتاج الزيتون والحبوب وتصديرها إلى روما.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/أبوليوس": [
    shortAnswer(-510,
      "من هو أبوليوس وبم اشتهر؟",
      "كاتب وفيلسوف لاتيني من مادور، اشتهر بكتابه «الحمار الذهبي».",
      "أبوليوس أديب من إفريقية الرومانية اشتهر برواية «الحمار الذهبي» وبخطاباته الفلسفية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/القديس أوغسطينوس": [
    shortAnswer(-511,
      "أين وُلد القديس أوغسطينوس؟",
      "في تاغست بإفريقية الرومانية.",
      "وُلد القديس أوغسطينوس في تاغست (سوق أهراس حالياً)، وكان من أهم آباء الكنيسة المسيحية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/القيروان قاعدة الانتشار العربي الإسلامي": [
    mcq(-512,
      "من المؤسس الأول لمدينة القيروان؟",
      ["موسى بن نصير", "عقبة بن نافع", "حسان بن النعمان", "طارق بن زياد"],
      "B",
      "أسّس عقبة بن نافع مدينة القيروان سنة 50 هـ / 670 م لتكون قاعدة للفتوحات الإسلامية في المغرب.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/الدور الاقتصادي للقيروان: أهمية النشاط التجاري": [
    shortAnswer(-513,
      "بم اشتهرت القيروان اقتصاديا في العصر الإسلامي؟",
      "بمكانتها التجارية بين المشرق والمغرب وإفريقيا جنوب الصحراء.",
      "كانت القيروان ملتقى للقوافل التجارية، تستقبل الذهب من بلاد السودان وتصدّر منتوجات إفريقية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/خصائص العمارة": [
    mcq(-514,
      "أي معلم يُعدّ رمزا للعمارة الإسلامية في القيروان؟",
      ["برج بيزا", "جامع عقبة بن نافع", "الكولوسيوم", "أهرامات الجيزة"],
      "B",
      "جامع عقبة بن نافع (الجامع الكبير) من أهم معالم العمارة الإسلامية في القيروان وفي إفريقية كلها.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/الإشعاع الفكري": [
    shortAnswer(-515,
      "اذكر مظهراً من مظاهر الإشعاع الفكري للقيروان.",
      "ازدهار مدارس الفقه واللغة والطب وانتشار العلماء كسحنون وابن أبي زيد.",
      "كانت القيروان مركزاً علمياً مهماً، اشتهرت بمدرسة سحنون الفقهية وبعلوم الطب واللغة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/عمارة مدينة تونس": [
    mcq(-516,
      "ما المعلم الذي يُعد رمزا للعمارة الحفصية في تونس؟",
      ["برج إيفل", "جامع الزيتونة وتطويره", "تاج محل", "قصر الحمراء"],
      "B",
      "ازدهر جامع الزيتونة في العهد الحفصي وأصبح مركزاً علمياً ودينياً مهماً في تونس.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/عبد الرحمان بن خلدون": [
    shortAnswer(-517,
      "بم اشتهر عبد الرحمان بن خلدون؟",
      "بكتاب «المقدمة» ووضعه أسس علم الاجتماع والعمران البشري.",
      "ابن خلدون مؤرخ تونسي الأصل، يُعدّ من مؤسسي علم الاجتماع التاريخي بفضل كتابه «المقدمة».",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/إضاءات حول تاريخ تونس في العصر الحديث": [
    shortAnswer(-518,
      "أيّ أسرة حاكمة سيطرت على تونس في بداية العصر الحديث؟",
      "الأسرة الحسينية (بعد المرادية).",
      "بعد المراديين، أسّس حسين بن علي الأسرة الحسينية التي حكمت تونس من 1705 حتى 1957.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/الفكر الإصلاحي": [
    shortAnswer(-519,
      "اذكر اسم مصلح تونسي من رواد الفكر الإصلاحي في القرن 19.",
      "خير الدين التونسي (أو أحمد بن أبي الضياف).",
      "خير الدين التونسي من أبرز المصلحين، صاحب كتاب «أقوم المسالك» الداعي إلى التحديث.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Histoire/التجربة التونسية في مقاومة الاستعمار": [
    mcq(-520,
      "متى نالت تونس استقلالها؟",
      ["1881", "1934", "1956", "1962"],
      "C",
      "نالت تونس استقلالها في 20 مارس 1956 بعد مفاوضات مع فرنسا.",
      { rtl: true, marks: 2 },
    ),
  ],
  "1ere_secondaire/Histoire/تعصير الدولة وتحديث المجتمع": [
    shortAnswer(-521,
      "اذكر مظهرا من مظاهر تحديث المجتمع التونسي بعد الاستقلال.",
      "إصلاح التعليم، مجلة الأحوال الشخصية، وتعميم التعليم العمومي.",
      "أصدرت تونس مجلة الأحوال الشخصية عام 1956 وعممت التعليم لكل الأطفال، كخطوات في تحديث المجتمع.",
      { rtl: true },
    ),
  ],
};

// ──────────────────────────────────────────────────────────────────────────────
// 1ÈRE SECONDAIRE — GÉOGRAPHIE (Arabic, RTL, ≥ 20 questions)
// ──────────────────────────────────────────────────────────────────────────────

const GEO_1ERE: Record<string, FallbackQuestion[]> = {
  "1ere_secondaire/Géographie/التوزع الجغرافي للسكان": [
    mcq(-601,
      "أي عنصر من العناصر التالية يندرج ضمن دراسة السكان؟",
      ["الحركة الديمغرافية", "التركيب الكيميائي للماء", "التفاعل الكهربائي", "المعادلات الرياضية"],
      "A",
      "تشمل دراسة السكان: التوزع، الكثافة، الحركة الديمغرافية، التركيبة العمرية والجنسية.",
      { rtl: true },
    ),
    shortAnswer(-602,
      "ما المقصود بالكثافة السكانية؟",
      "عدد السكان بالنسبة إلى مساحة المكان (نسمة/كم²).",
      "تُحسب الكثافة السكانية بقسمة عدد السكان على مساحة الإقليم.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/الحركة الديمغرافية للسكان": [
    mcq(-603,
      "تتعلق الحركة الديمغرافية أساسا بـ:",
      ["الولادات والوفيات والهجرة", "أنواع المعادن", "نسبة الأمطار", "أنواع المحاصيل"],
      "A",
      "الحركة الديمغرافية تشمل المواليد والوفيات والنمو الطبيعي والهجرة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/الحركية المجالية للسكان": [
    shortAnswer(-604,
      "ما المقصود بالهجرة الداخلية؟",
      "انتقال السكان داخل البلد نفسه من منطقة إلى أخرى.",
      "الهجرة الداخلية تنقل السكان من الريف إلى المدينة أو بين الجهات داخل الدولة الواحدة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/الانفجار الحضري": [
    mcq(-605,
      "أحد أسباب الانفجار الحضري في البلدان النامية:",
      ["انخفاض النمو السكاني", "الهجرة الريفية نحو المدن", "نقص المساكن في الريف", "غياب الزراعة"],
      "B",
      "تنمو المدن في البلدان النامية بسبب الهجرة الريفية الحضرية والنمو الطبيعي السريع.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/تركيبة المدينة: دراسة حالة: القاهرة": [
    shortAnswer(-606,
      "اذكر مشكلة حضرية تواجه مدينة القاهرة.",
      "الاكتظاظ السكاني وضعف البنية التحتية والتلوث.",
      "تعاني القاهرة من اكتظاظ سكاني هائل وضغط على النقل والسكن والخدمات.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/الموارد المائية": [
    mcq(-607,
      "أكبر نسبة من المياه على سطح الأرض هي:",
      ["مياه عذبة في الأنهار", "مياه مالحة في المحيطات", "ثلوج فقط", "بحيرات داخلية"],
      "B",
      "تشكّل المحيطات حوالي 97 % من المياه على الأرض وهي مياه مالحة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/الموارد المائية وتوزعها الجغرافي": [
    shortAnswer(-608,
      "ما المقصود بالعجز المائي؟",
      "الفرق بين الطلب على الماء والموارد المتوفرة عندما يفوق الطلبَ العرضُ.",
      "يحدث العجز المائي عندما تفوق احتياجات السكان والأنشطة الاقتصادية الموارد المتاحة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/تعبئة المياه": [
    mcq(-609,
      "أحد وسائل تعبئة المياه:",
      ["استخراج النفط", "بناء السدود وتحلية مياه البحر", "زراعة القمح فقط", "صناعة السيارات"],
      "B",
      "تشمل وسائل تعبئة المياه بناء السدود والآبار وتحلية مياه البحر ومعالجة المياه المستعملة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/رهانات الماء": [
    shortAnswer(-610,
      "اذكر رهاناً مهماً يتعلق بإدارة الماء في تونس.",
      "ندرة الموارد المائية والتغير المناخي والاستهلاك المتزايد.",
      "تواجه تونس تحديات الندرة المائية والتغير المناخي وتزايد الطلب الفلاحي والصناعي.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/الموارد النفطية": [
    mcq(-611,
      "النفط مورد طاقي:",
      ["متجدد", "غير متجدد", "بلا حدود", "نباتي"],
      "B",
      "النفط مورد أحفوري غير متجدد، يتكوّن في باطن الأرض على ملايين السنين.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/الموارد النفطية: الإنتاج والاستهلاك والمبادلات": [
    shortAnswer(-612,
      "أيّ منطقة في العالم تُعدّ من أكبر مناطق إنتاج النفط؟",
      "الشرق الأوسط (الخليج العربي).",
      "تنتج دول الخليج كالسعودية والإمارات والعراق وإيران كميات كبيرة من النفط العالمي.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/رهانات النفط": [
    shortAnswer(-613,
      "اذكر رهاناً مهمّاً مرتبطاً بالنفط.",
      "التقلبات في الأسعار والتلوث والاعتماد الاقتصادي على هذا المورد.",
      "النفط مورد استراتيجي يثير رهانات بيئية واقتصادية وجيوسياسية مهمة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/الإنسان والوسط الطبيعي": [
    mcq(-614,
      "علاقة الإنسان بالوسط الطبيعي هي علاقة:",
      ["انفصال تام", "تأثير متبادل وتفاعل", "خضوع كلي للطبيعة فقط", "لا توجد أي علاقة"],
      "B",
      "يؤثر الإنسان في الوسط الطبيعي ويتأثر به: استغلال للموارد ومخاطر طبيعية وتلوث.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/من المخاطر إلى الكوارث: الزلازل والبراكين": [
    mcq(-615,
      "الزلزال هو:",
      ["هطول الأمطار الغزيرة", "اهتزاز سطح الأرض نتيجة حركة الصفائح", "ارتفاع درجة الحرارة", "هبوب الرياح"],
      "B",
      "الزلزال اهتزاز مفاجئ للأرض نتيجة حركة الصفائح التكتونية وتحرر الطاقة المخزّنة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/من المخاطر إلى الكوارث: الفيضانات": [
    shortAnswer(-616,
      "اذكر سبباً طبيعياً من أسباب الفيضانات.",
      "الأمطار الغزيرة والمفاجئة، وذوبان الثلوج.",
      "تحدث الفيضانات بسبب أمطار غزيرة، أو ذوبان الثلوج، أو فيضان الأنهار.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/تدهور الأوساط الطبيعية: مثال التصحر": [
    mcq(-617,
      "التصحر هو:",
      ["تحول الصحراء إلى غابات", "تدهور التربة في المناطق الجافة وامتداد الصحراء", "هطول الثلوج كثيرا", "زيادة الزراعة"],
      "B",
      "التصحر يعني تراجع جودة التربة وقدرتها الإنتاجية، خاصة في المناطق شبه الجافة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/تدهور الأوساط الطبيعية: مثال تدهور الغابة المتوسطية": [
    shortAnswer(-618,
      "اذكر عاملاً بشرياً يساهم في تدهور الغابات المتوسطية.",
      "الحرائق المفتعلة والرعي الجائر والقطع العشوائي.",
      "تتعرض الغابات المتوسطية لضغط بشري كبير: حرائق، قطع، رعي مفرط.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/تدهور الأوساط الطبيعية: تعرية السواحل": [
    shortAnswer(-619,
      "ما المقصود بتعرية السواحل؟",
      "تراجع الخط الساحلي بفعل الأمواج والتيارات والأنشطة البشرية.",
      "تتعرض السواحل لعمليات تعرية مستمرة بسبب الأمواج وارتفاع منسوب البحر والبناء غير المنظّم.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Géographie/الخضرسة": [
    mcq(-620,
      "الخضرسة هي:",
      ["تجفيف المسطحات المائية", "نقص الأكسجين في الماء بسبب التلوث", "زيادة ملوحة التربة", "ارتفاع درجة الحرارة"],
      "B",
      "الخضرسة ظاهرة تتعلق بانتشار الطحالب وتراجع جودة الماء بسبب التلوث وزيادة المغذيات.",
      { rtl: true },
    ),
  ],
};

// ──────────────────────────────────────────────────────────────────────────────
// 1ÈRE SECONDAIRE — TECHNIQUE (≥ 18 questions)
// ──────────────────────────────────────────────────────────────────────────────

const TECHNIQUE_1ERE: Record<string, FallbackQuestion[]> = {
  "1ere_secondaire/Technique/Analyse fonctionnelle d'un système technique": [
    mcq(-701,
      "À quoi sert l'analyse fonctionnelle d'un système technique ?",
      ["À décorer le système", "À identifier les fonctions que le système doit assurer", "À calculer uniquement son prix", "À supprimer toutes ses pièces"],
      "B",
      "L'analyse fonctionnelle décrit les fonctions de service et techniques que le système doit remplir pour satisfaire un besoin.",
    ),
    shortAnswer(-702,
      "Quel outil graphique permet de représenter les fonctions d'un produit et son environnement ?",
      "Le diagramme « pieuvre » (ou diagramme des fonctions de service).",
      "Le diagramme pieuvre représente le produit au centre et ses fonctions de service en relation avec les éléments du milieu extérieur.",
    ),
  ],
  "1ere_secondaire/Technique/Lecture d'un dessin d'ensemble": [
    mcq(-703,
      "Un dessin d'ensemble permet de :",
      ["représenter une seule pièce détaillée", "représenter l'assemblage de plusieurs pièces", "concevoir un site web", "réaliser une carte de géographie"],
      "B",
      "Un dessin d'ensemble montre l'assemblage des différentes pièces d'un mécanisme avec une nomenclature.",
    ),
  ],
  "1ere_secondaire/Technique/Graphe de montage et graphe de démontage": [
    shortAnswer(-704,
      "À quoi sert un graphe de montage ?",
      "À indiquer l'ordre dans lequel les pièces doivent être assemblées.",
      "Le graphe de montage décrit la séquence d'assemblage des pièces pour réaliser un mécanisme.",
    ),
  ],
  "1ere_secondaire/Technique/Dessin de définition": [
    mcq(-705,
      "Le dessin de définition représente :",
      ["plusieurs pièces assemblées", "une seule pièce avec toutes ses cotes", "un planning de production", "un schéma électrique"],
      "B",
      "Le dessin de définition est un dessin technique d'une seule pièce, avec ses dimensions, tolérances et matériaux.",
    ),
  ],
  "1ere_secondaire/Technique/Dessin assisté par ordinateur (DAO)": [
    mcq(-706,
      "Le DAO désigne :",
      ["le Dessin Assisté par Ordinateur", "le Désassemblage Automatique Optimisé", "la Découpe Adaptative d'Origine", "le Diagramme Avancé d'Outils"],
      "A",
      "Le DAO (Dessin Assisté par Ordinateur) utilise un logiciel pour réaliser des plans techniques avec précision.",
    ),
  ],
  "1ere_secondaire/Technique/Liaisons mécaniques": [
    mcq(-707,
      "Une liaison « pivot » entre deux pièces permet :",
      ["aucun mouvement", "une rotation autour d'un axe", "une translation libre dans toutes les directions", "uniquement un déplacement vertical"],
      "B",
      "Une liaison pivot autorise uniquement une rotation entre deux pièces autour d'un axe commun.",
    ),
  ],
  "1ere_secondaire/Technique/Systèmes combinatoires": [
    mcq(-708,
      "Dans un système combinatoire, la sortie dépend :",
      ["uniquement de l'état passé", "uniquement de l'état actuel des entrées", "du temps écoulé seulement", "de la couleur du circuit"],
      "B",
      "Un système combinatoire fournit une sortie qui ne dépend que de l'état actuel des entrées, sans mémoire.",
    ),
  ],
  "1ere_secondaire/Technique/Transmission de puissance": [
    mcq(-709,
      "Quel système permet de transmettre un mouvement de rotation entre deux arbres parallèles ?",
      ["Un engrenage", "Une éprouvette", "Une boussole", "Un microscope"],
      "A",
      "Un engrenage (ou une courroie, une chaîne) transmet la rotation entre arbres avec un rapport défini.",
    ),
  ],
  "1ere_secondaire/Technique/Matériaux utilisés": [
    mcq(-710,
      "Lequel de ces matériaux est un métal ?",
      ["Le verre", "Le bois", "L'aluminium", "Le plastique"],
      "C",
      "L'aluminium est un métal léger et conducteur ; le verre, le bois et le plastique ne sont pas des métaux.",
    ),
    shortAnswer(-711,
      "Cite une propriété importante à considérer lors du choix d'un matériau.",
      "La résistance mécanique, la masse, le coût ou la résistance à la corrosion.",
      "Les ingénieurs choisissent les matériaux en fonction de propriétés mécaniques, thermiques, économiques et environnementales.",
    ),
  ],
  "1ere_secondaire/Technique/Énergies renouvelables": [
    mcq(-712,
      "Laquelle de ces sources d'énergie est renouvelable ?",
      ["Le pétrole", "Le charbon", "L'énergie solaire", "Le gaz naturel"],
      "C",
      "Les énergies renouvelables comprennent le solaire, l'éolien, l'hydraulique, la biomasse et la géothermie.",
    ),
  ],
  "1ere_secondaire/Technique/Convertisseurs statiques d'énergie électrique": [
    mcq(-713,
      "Un convertisseur statique d'énergie électrique permet de :",
      ["transformer une forme d'énergie électrique en une autre", "fabriquer du carburant", "produire de l'eau", "remplacer une batterie chimique"],
      "A",
      "Un convertisseur statique change la forme (alternatif/continu, tension, fréquence) de l'énergie électrique sans pièces mobiles.",
    ),
  ],
  "1ere_secondaire/Technique/Projet 1: Robot suiveur de ligne et éviteur d'obstacles": [
    mcq(-714,
      "Quel capteur permet à un robot suiveur de ligne de détecter la ligne au sol ?",
      ["Un capteur infrarouge", "Un microphone", "Une caméra thermique uniquement", "Un altimètre"],
      "A",
      "Un capteur infrarouge mesure la réflexion sur le sol et différencie la ligne (sombre) du fond (clair).",
    ),
  ],
  "1ere_secondaire/Technique/Programmation d'une carte de commande d'un système embarqué": [
    shortAnswer(-715,
      "Cite un exemple de carte programmable utilisée en système embarqué dans les projets scolaires.",
      "La carte Arduino (ou Micro:bit, Raspberry Pi Pico).",
      "Les cartes Arduino sont fréquemment utilisées dans les projets scolaires pour contrôler capteurs et actionneurs.",
    ),
  ],
  "1ere_secondaire/Technique/Procédés de mise en forme des matériaux": [
    mcq(-716,
      "Lequel des procédés suivants permet de mettre en forme une pièce métallique ?",
      ["Le sciage", "La pyrolyse uniquement", "La danse", "Le tricotage"],
      "A",
      "Le sciage, l'usinage, le pliage, le moulage et l'extrusion sont des procédés de mise en forme des matériaux.",
    ),
  ],
  "1ere_secondaire/Technique/Procédés et typologie des assemblages": [
    mcq(-717,
      "Le rivetage est un assemblage :",
      ["démontable sans destruction", "non démontable (permanent)", "magnétique", "totalement réversible"],
      "B",
      "Le rivetage est un assemblage non démontable : pour défaire l'assemblage, il faut détruire le rivet.",
    ),
  ],
  "1ere_secondaire/Technique/Contrôle des composants": [
    shortAnswer(-718,
      "Pourquoi contrôle-t-on un composant après sa fabrication ?",
      "Pour vérifier sa conformité aux exigences (dimensions, qualité, fonctionnement).",
      "Le contrôle qualité garantit que le composant répond aux spécifications avant son assemblage.",
    ),
  ],
  "1ere_secondaire/Technique/Projet 2: Lampe connectée": [
    mcq(-719,
      "Une lampe connectée peut être contrôlée :",
      ["uniquement par un interrupteur mural", "à distance par un smartphone ou une application", "uniquement par la voix d'une personne précise", "uniquement avec une télécommande infrarouge"],
      "B",
      "Une lampe connectée est pilotable via un smartphone ou un assistant vocal grâce à une connexion Wi-Fi ou Bluetooth.",
    ),
  ],
  "1ere_secondaire/Technique/Fonction interfaçage": [
    shortAnswer(-720,
      "Quel est le rôle d'une interface dans un système technique ?",
      "Faire le lien entre l'utilisateur (ou un autre système) et le système, en adaptant les signaux ou commandes.",
      "L'interface adapte les signaux entre l'utilisateur, les capteurs/actionneurs et le système de commande.",
    ),
  ],
};

// ──────────────────────────────────────────────────────────────────────────────
// 1ÈRE SECONDAIRE — ÉDUCATION ISLAMIQUE (Arabic, RTL, ≥ 20 questions)
// ──────────────────────────────────────────────────────────────────────────────

const ISLAM_1ERE: Record<string, FallbackQuestion[]> = {
  "1ere_secondaire/Éducation Islamique/تلازم أركان العقيدة": [
    mcq(-801,
      "أركان العقيدة الإسلامية مترابطة فيما بينها لأنها:",
      ["مستقلة لا علاقة بينها", "متلازمة لا يستقيم بعضها دون بعض", "اختيارية كلها", "متعارضة"],
      "B",
      "أركان العقيدة الإسلامية (الإيمان بالله، الملائكة، الكتب، الرسل، اليوم الآخر، القدر) مترابطة لا تنفصل.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/الإيمان عقيدة وممارسة": [
    mcq(-802,
      "ما المقصود بالإيمان عقيدة وممارسة؟",
      ["أن الإيمان قول فقط", "أن الإيمان اعتقاد ينعكس على السلوك والعمل", "أن الإيمان لا علاقة له بالأخلاق", "أن الإيمان يقتصر على المعرفة النظرية"],
      "B",
      "الإيمان في الإسلام لا يقتصر على الاعتقاد بالقلب، بل يجب أن ينعكس في القول والعمل والسلوك.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/الإيمان حسن المعاملة: هدي قرآني": [
    shortAnswer(-803,
      "اذكر آية أو معنى آية تربط بين الإيمان وحسن المعاملة.",
      "قوله تعالى: «من كان يؤمن بالله واليوم الآخر فلْيُكرم جاره».",
      "يربط القرآن والسنة الإيمانَ بحسن معاملة الجار والأهل والناس عامة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/تكامل العقل والنقل في إثبات حقيقة الغيب": [
    mcq(-804,
      "ما العلاقة بين العقل والنقل في إثبات الغيب؟",
      ["العقل يكفي وحده", "النقل وحده يكفي", "العقل والنقل متكاملان", "لا علاقة بينهما"],
      "C",
      "العقل والنقل (الوحي) متكاملان: العقل يدرك الدلائل، والوحي يكشف عن حقائق الغيب التي لا يبلغها العقل وحده.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/طبيعة العلاقات الأسرية في الإسلام": [
    shortAnswer(-805,
      "اذكر قيمة من قيم العلاقات الأسرية في الإسلام.",
      "المودة والرحمة والاحترام المتبادل.",
      "أسس الإسلام علاقات الأسرة على المودة والرحمة والتعاون.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/دور الأسرة في الارتقاء بالعلاقات الاجتماعية": [
    mcq(-806,
      "أهم وظيفة اجتماعية للأسرة:",
      ["زيادة عدد السكان فقط", "تنشئة الأبناء على القيم والسلوك القويم", "الاستهلاك الكثير", "الانعزال عن المجتمع"],
      "B",
      "تربية الأبناء على القيم والأخلاق هي إحدى أهم وظائف الأسرة الاجتماعية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/المجادلة بالحسنى: هدي قرآني": [
    shortAnswer(-807,
      "ما المقصود بالمجادلة بالحسنى؟",
      "الحوار بالحجة والكلمة الطيبة بعيدا عن العنف والإهانة.",
      "أمر القرآن بالحوار بالحسنى: «وجادلهم بالتي هي أحسن».",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/آداب الحوار": [
    mcq(-808,
      "من آداب الحوار في الإسلام:",
      ["مقاطعة المتحدث دائماً", "الإصغاء للآخر واحترام رأيه", "السخرية من المخالف", "رفع الصوت"],
      "B",
      "من آداب الحوار: الإصغاء، احترام الرأي الآخر، الكلمة الطيبة، وعدم المقاطعة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/أثر الحوار في تحقيق التواصل بين الأجيال": [
    shortAnswer(-809,
      "كيف يحقق الحوار التواصل بين الأجيال؟",
      "بفهم وجهات النظر المختلفة والتقريب بين الآباء والأبناء.",
      "الحوار الإيجابي يقلّل الفجوة بين الأجيال ويعزز فهم الخصوصيات والقيم.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/أثر الإيمان في العلاقات الاجتماعية: هدي نبوي": [
    mcq(-810,
      "أثر الإيمان في علاقات المؤمن مع الناس هو:",
      ["العزلة عنهم", "حسن معاملتهم ونفعهم", "الاستعلاء عليهم", "ظلمهم"],
      "B",
      "المؤمن يعامل الناس بالعدل والإحسان وينفعهم؛ والنبي ﷺ قال: «خير الناس أنفعهم للناس».",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/حقيقة النبوّة ومقتضياتها": [
    shortAnswer(-811,
      "ما المقصود بالنبوة؟",
      "اصطفاء الله بعض البشر لإبلاغ رسالته وهداية الناس.",
      "النبوة منزلة سامية يصطفي الله لها بعض عباده لتبليغ الوحي.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/دور الأنبياء في الارتقاء بالوعي البشري": [
    mcq(-812,
      "أحد أدوار الأنبياء:",
      ["ترك الناس على ما هم عليه", "إرشاد الناس إلى التوحيد ومكارم الأخلاق", "نشر الجهل", "تعميق الخلافات"],
      "B",
      "الأنبياء يدعون إلى التوحيد وحسن الأخلاق وإصلاح المجتمعات.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/النبوّة هداية وإصلاح: هدي قرآني": [
    shortAnswer(-813,
      "بِم وصف القرآن رسالة الأنبياء؟",
      "بأنها هداية ورحمة وإصلاح للناس.",
      "وصف القرآن الأنبياء بأنهم بشّروا وأنذروا ودعوا إلى الخير والإصلاح.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/الأنبياء بناة الحضارة: هدي نبوي": [
    mcq(-814,
      "أسهم الأنبياء في بناء الحضارة من خلال:",
      ["تشجيع التخلف", "نشر العلم والقيم والعدل", "العزلة الكاملة عن المجتمع", "محاربة العلم"],
      "B",
      "ساهم الأنبياء ببناء أسس حضارة قائمة على العلم والقيم والعدل والإصلاح.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/الاجتهاد ضرورة شرعية: هدي نبوي": [
    shortAnswer(-815,
      "لماذا يُعد الاجتهاد ضرورة شرعية؟",
      "لأن المسائل المستجدة تحتاج إلى أحكام جديدة في ضوء الكتاب والسنة.",
      "الاجتهاد ضروري لأن الواقع يتغير ويظهر مستجدات تحتاج إلى أحكام شرعية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/التشريع بالنص": [
    mcq(-816,
      "التشريع بالنص يعني الاستناد إلى:",
      ["العادات فقط", "القرآن والسنة", "القياس فقط", "الرأي الشخصي"],
      "B",
      "التشريع بالنص يعتمد على النصوص الشرعية من القرآن والسنة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/التشريع بالاجتهاد المستند إلى أصل سابق": [
    shortAnswer(-817,
      "اذكر مثالا لمصدر اجتهاد مستند إلى أصل سابق.",
      "القياس على حكم ثابت في القرآن أو السنة.",
      "القياس هو ربط حكم مسألة جديدة بحكم مسألة منصوصة لاشتراكهما في العلة.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/التشريع بالاستحسان والرأي المستند إلى المصلحة": [
    mcq(-818,
      "الاستحسان في الفقه الإسلامي يعني:",
      ["استبدال الشرع بالعقل", "ترجيح دليل على آخر لمصلحة ظاهرة", "إلغاء الأحكام كلها", "التقليد الأعمى"],
      "B",
      "الاستحسان هو ترجيح حكم لمصلحة معتبرة وفق ضوابط شرعية.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/خصائص الشريعة الإسلامية": [
    mcq(-819,
      "من خصائص الشريعة الإسلامية:",
      ["الجمود وعدم القابلية للتطبيق", "الشمول والمرونة والوسطية", "الانفصال عن الواقع", "تعقيد الأحكام"],
      "B",
      "الشريعة الإسلامية تتميز بالشمول والوسطية والمرونة لتلبية حاجات الناس في كل زمان ومكان.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/قيمة العمل في الإسلام": [
    shortAnswer(-820,
      "كيف ينظر الإسلام إلى العمل؟",
      "يعدّه عبادة وقيمة حضارية وسبيلا لكسب الرزق الحلال.",
      "العمل في الإسلام عبادة وضرورة اجتماعية، ووسيلة للارتقاء بالفرد والمجتمع.",
      { rtl: true },
    ),
  ],
  "1ere_secondaire/Éducation Islamique/دور العمل في تحقيق الذات": [
    mcq(-821,
      "العمل يحقق الذات لأنه:",
      ["يجعل الإنسان كسولاً", "ينمّي القدرات ويعزز الثقة بالنفس والاستقلالية", "يحد من إبداع الإنسان", "يخفّض الكرامة"],
      "B",
      "العمل ينمّي مهارات الإنسان ويعزّز ثقته بنفسه واستقلاليته الاقتصادية والاجتماعية.",
      { rtl: true },
    ),
  ],
};

// ──────────────────────────────────────────────────────────────────────────────
// AGGREGATED EXPORT
// ──────────────────────────────────────────────────────────────────────────────

import { QUESTIONS_FALLBACK_2EME } from "./questionsFallback2eme";
import { QUESTIONS_FALLBACK_3EME } from "./questionsFallback3eme";

export const QUESTIONS_FALLBACK: Record<string, FallbackQuestion[]> = {
  ...MATH_1ERE,
  ...PHYSIQUE_1ERE,
  ...SVT_1ERE,
  ...FRANCAIS_1ERE,
  ...HISTOIRE_1ERE,
  ...GEO_1ERE,
  ...TECHNIQUE_1ERE,
  ...ISLAM_1ERE,
  ...QUESTIONS_FALLBACK_2EME,
  // 3eme questions use "__special__" keys for branch-shared subjects. The frontend
  // fallback lookup will not find them via getFallbackQuestions() — that's fine,
  // they live in Neon post-seed. They're spread here so the keys are still
  // type-checked by TypeScript at build time.
  ...QUESTIONS_FALLBACK_3EME,
};

export function getFallbackQuestions(
  levelCode: string,
  subject: string,
  topic: string,
  sectionKey?: string | null,
): FallbackQuestion[] {
  if (sectionKey) {
    const key = `${levelCode}/${sectionKey}/${subject}/${topic}`;
    if (QUESTIONS_FALLBACK[key]) return QUESTIONS_FALLBACK[key];
  }
  return QUESTIONS_FALLBACK[`${levelCode}/${subject}/${topic}`] ?? [];
}

export function getQualitativeFeedback(score: number, total: number): string {
  if (total === 0) return "Aucune question évaluée.";
  const pct = score / total;
  if (pct >= 0.85) return "Très bon travail ! Vous maîtrisez bien ce chapitre.";
  if (pct >= 0.65) return "Bon travail. Quelques notions sont encore à renforcer.";
  if (pct >= 0.40) return "Résultats mitigés. Nous vous conseillons de refaire quelques exercices.";
  return "Vous devriez réviser davantage ce chapitre avant de continuer.";
}
